### ISSUE TITLE
sum of a vector

### ISSUE THREAD

**Issue by bnicenboim** [r-cas/caracas#22]
Ok, I've tried to do the same here as in https://github.com/r-cas/ryacas/issues/51

<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" title="\sum_{i=1}^{n} x_{N-2 \cdot(i-1)}" /></a>

But with no success, I would guess this should work, but it doesn't:

```
library(caracas)
library(dplyr)
N <- 20
x <- paste0("x_", 1:N) %>% as_symbol()
n <- symbol("n")
i <- symbol("i")
sumf(x[N - 2 * (i-1)],var = "i", 1, n)
```

**Comment by mikldk** [comment]
Maybe something like this?

``` r
library(caracas)
j <- symbol("j")
xj <- eval_to_symbol("Indexed('x', j)")
xj
#> [caracas]: x[j]
n <- symbol("n")
e <- sumf(xj, var = "j", lower = 1, upper = n, doit = FALSE)
e
#> [caracas]:   n       
#>             ___      
#>             ╲        
#>              ╲       
#>              ╱   x[j]
#>             ╱        
#>             ‾‾‾      
#>            j = 1
tex(e)
#> [1] "\\sum_{j=1}^{n} {x}_{j}"
```

**Comment by bnicenboim** [comment]
Great, thanks!

If I do this instead it works as I wanted
```
N <- symbol("N")
j <- symbol("j")
xj <- eval_to_symbol("Indexed('x', N-2*(j-1))")
n <- symbol("n")
e <- sumf(xj, var = "j", lower = 1, upper = n, doit = FALSE)
e
```
Now one problem is that for both my and your example `as_r(e)` doesn't work.

And a follow up question is there a way to indicate what are the elements inside the vector `x`. 
That is to combine the previous lines with the following 
```
x <- paste0("x_", 1:50) %>% as_symbol()
```
I would like to be able to also set `N` and `n` to some number in the `sumf`, and see what happens with the sum for some arbitrary values.

**Comment by mikldk** [comment]
I think maybe it is time to step back. I am not sure I understand what you would like to do. Can you try to explain it from the beginning and give an example or two?

**Comment by bnicenboim** [comment]
ok, sure, this is a simplification of my real case, but say that

X = x_1, x_2, ..., x_N

I would like to get the general case of a sum that of n elements in steps of two that starts in N, basically the following equation:


<a href="https://www.codecogs.com/eqnedit.php?latex=\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sum_{i=1}^{n}&space;x_{N-2&space;\cdot(i-1)}" title="\sum_{i=1}^{n} x_{N-2 \cdot(i-1)}" /></a>

I achieved this adapting your code:

```
> e
[caracas]:   n                 
            ___                
            ╲                  
             ╲   x[N - 2*j + 2]
             ╱                 
            ╱                  
            ‾‾‾                
           j = 1
> 
```


But also I'd like to be able to set N and n to different numbers and see what is the sum I get, for example if N= 20 and n =4, I should be able to get this specific case:

```
"x[18]+x[16]+x[14]+x[12]"
```


Is it clearer? 

(Thanks for taking your time to go over this!)

**Comment by mikldk** [comment]
I am just trying to understand why you need symbolic math -- the `x`'s are unknown.

What about something `base` like:
``` r
n <- 4
N <- 20
e <- N - 2*(1:n) + 2
e
#> [1] 20 18 16 14
paste0("x[", e, "]", collapse = " + ")
#> [1] "x[20] + x[18] + x[16] + x[14]"
```

**Comment by bnicenboim** [comment]
Yes, I know I can do it like that.
 I need symbolic math, because in reality I have a ton of terms (sums that go on different steps and elements of different variables), and I want to have the general case for coding a for loop (It's the likelihood of a hidden markov model).  But I want to be able to verify that my logic holds for simple cases, that I can do by hand.

But in any case I managed to do it!!! But there is a bug and some issues, though

This works:

```
N <- symbol("N")
n <- symbol("n")
j <- symbol("j")
xj <- eval_to_symbol("Indexed('x', N-2*(j-1))")
e <- sumf(xj, var = "j", lower = 1, upper = n, doit = TRUE)
e
[caracas]:   n                 
            ___                
            ╲                  
             ╲   x[N - 2*j + 2]
             ╱                 
            ╱                  
            ‾‾‾                
           j = 1
n <- 4L
N <- 20L
xj <- xj %>% subs("N", N)
e_s <- sumf(xj, var = "j", lower = 1, upper = 4, doit = TRUE)
e_s
[caracas]: x[14] + x[16] + x[18] + x[20
```

1. but strangely enough, this doesn't replace n for 4:
```
e_s <- sumf(xj, var = "j", lower = 1, upper = n, doit = TRUE)
```

2. It maybe good if `subs` assumes that round numbers are integers (so that the user doesn't need to include L), maybe using `rlang::is_integerish()`

3. It could be useful to use ``[[ `()` as  Indexed. 

If you think these are reasonable requests I'll close this, and I'll open different issues.

**Comment by mikldk** [comment]
Again, thanks. Sorry about the delay.

1. Is because at some point I tried enabling non-standard evaluation. I disabled that again in 36e70fb.
2. and 3.: Yes, please open separate issues.
