### ISSUE TITLE
Multiple linear equations solving not working

### ISSUE THREAD

**Issue by mckraqs** [r-cas/caracas#24]
Hi,

I'm having troubles in solving more than 1 linear equation via `solve_sys`. Can u help me with that? Everything relies on converting everything into `lhs-rhs` but for many equations it doesn't work for vectors, matrices, neither lists..

Simple example below, which should work, even for single equation inside lists:
```
x <- symbol('x')
exp1 <- 2*x +2
exp2 <- x

solve_sys(c(exp1), c(exp2), x)
```

An error I get is: `Error in lhs - rhs : non-numeric argument to binary operator`, so it indicates on elementwise subtraction error.

**Comment by mckraqs** [comment]
Alright, after diving into your internal tests I have found what I was interested in, i.e.
`solve_sys(t(as_symbol(matrix("2*x+2"))), t(as_symbol(matrix("x"))), c("x"))`

If I were you, I would consider more versatile examples. `test-solve.R` was the only place I could found any information about that functionality.

**Comment by mikldk** [comment]
Thanks. I agree that the documentation should be better, so I'll reopen this issue. Thank you for reporting this.

**Comment by mikldk** [comment]
You should just use `solve_sys(cbind(exp1), cbind(exp2), x)`. I added the example in a027f4b.
