### ISSUE TITLE
Cannot use sympy$sympify

### ISSUE THREAD

**Issue by psads-git** [r-cas/caracas#55]
I am trying to run the following code, but I get the indicated error. Could you please help me?

``` r
library(caracas)
sympy <- get_sympy()
sympy$sympify('2**2 / 3 + 5', evaluate=False)
#> Error in py_resolve_dots(list(...)): object 'False' not found
```

**Comment by mikldk** [comment]
Try the `R` value `FALSE` instead of `False`. Does that help?

**Comment by psads-git** [comment]
Yes, Mikkel! Thanks! Meanwhile, I opened another issue on reticulate, a the same issue occurs:

https://github.com/rstudio/reticulate/issues/1100
