### ISSUE TITLE
Symbolic in R: "expression" --> provide `as.expression()` and possibly `as.function()` methods for caracas objects

### ISSUE THREAD

**Issue by mmaechler** [r-cas/caracas#75]
(see title).  You have your own generic `as_expr()` where really knowing R well, as user I'd "expect" `as.expression(<caracas_symbol>)` to work.
Further, base R has always had `as.function()`; though it has not been used extensively, but e.g. in package `polynom`.

**Comment by mikldk** [comment]
Thanks for reporting this, @mmaechler . Both a good suggestions, and I am embarrassed that we do not have them. Will implement them right away.

**Comment by mikldk** [comment]
@mmaechler The newest commit solves this. Thanks for reporting. I will close this now. Please feel free to re-open if you experience any problems (or open new issues with other suggestions/questions).

**Comment by mikldk** [comment]
@mmaechler FYI: Today the newest version, 2.1.1, was uploaded to CRAN and it contains this patch.
